### ISSUE TITLE
Toml

### ISSUE THREAD

**Issue by ratmice** [pchampin/ld0#1]
It's perhaps also interesting to weigh Toml as an option along with Yaml/Hjson, As it directly translates to json as well.

It looks like in Hjson, while you can do unquoted `@`, you would still need to quote something like: `foo:bar : "baz"` as it is, that expands to: `"foo": "bar : \"baz\""`

If we took Toml and relaxed the _bare key_ rules (unquoted), to allow for `@` and `:`, Colon specifically wouldn't clash like it does in Hjson, because Toml uses `=` instead of `:` as it's grammar for binding keys to values.

Edit: removed `@` from `@foo:bar`

**Comment by pchampin** [comment]
Thanks for this suggestion, this is indeed something worth considering.

That being said, I'm not quite  comfortable with TOML for this use case.
For example, consider the following JSON:
```json
{
  "id": "#pa",
  "firstName": "Pierre-Antoine",
  "knows": {
    "id": "#cygri",
    "fisrtName": "Richard",
    "knows": {
      "id": "#andy",
      "firstName": "Andy"
    }
  }
}
```

It would translate either to
```toml
id = "#pa"
firstName = "Pierre-Antoine"
knows.id = "#cygri"
knows.firstName = "Richard"
knows.knows.id = "#andy"
knows.knows.firstName = "Andy"
```
which is verbose, or to
```toml
id = "#pa"
firstName = "Pierre-Antoine"
[knows]
id = "#cygri"
firstName = "Richard"
[knows.knows]
id = "#andy"
firstName = "Andy"
```
which differentiates properties (e.g. firstName vs. knows) in an unnatural way, and makes the embedding less obvious.
